dotnet: 1.0.0-rc4-004771
language: csharp

cache:
  directories:
  - src/packages
  - tools

before_script:
 - chmod +x build.sh

script:
  - ./build.sh

notifications:
  email:
    on_success: change
