language: csharp
mono: none
dotnet: 3.1.5
dist: trusty

cache:
  directories:
  - src/packages
  - tools

before_script:
 - chmod +x build.sh

script:
  - ./build.sh

notifications:
  email:
    on_success: change
