name: Check format

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: actions/setup-dotnet@v1
          # with:
            # dotnet-version: 3.1.x

      - uses: xt0rted/dotnet-format-problem-matcher@v1.2.0

      - run: dotnet tool install -g dotnet-format

      - run: dotnet format --check src
